### ISSUE TITLE
bunker stuff

### ISSUE THREAD

**Issue by davedumas0** [friendsincode/DeadZoneRP#14]
things for only certain people(server owner) to have "control" of the bunker

**Comment by davedumas0** [comment]
1. - [ ] small missions(run small amounts drugs to a boat in the ocean) 

2. - [ ]  after player reaches a certain "rank" in the bunker "new" harder missions become available

**Comment by davedumas0** [comment]
small missions to start and large complicated missions to  "build" up player to kingpin status

**Comment by chrobione** [comment]
moved...
